# Generated by Django 5.1.1 on 2024-10-06 19:42

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='title',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='change_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='change_description',
            field=models.TextField(default=datetime.datetime(2024, 10, 6, 19, 42, 32, 954379, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
